dataset_name: 'retina_GA'
target_dim: (512, 512)
dataset_path: '$ROOT/data/retina_GA/'
model_save_path: '$ROOT/checkpoints/retina_GA_seed1.pty'
output_save_path: '$ROOT/results/retina_GA_seed1/'
log_folder: '$ROOT/logs'
learning_rate: 1e-3
max_epochs: 200
patience: 10
batch_size: 16
num_filters: 16
sample_pairs: True        # Equal prob. for each patient during training.
ode_augment_dim: 1        # Augmented Neural ODE: additional dimension.
ode_tol: 1e-3             # Neural ODE: tolerance.
ode_adjoint: False        # Neural ODE: Whether to use the adjoint method.
ode_time_dependent: True  # Neural ODE: Whether it is time-dependent.
ode_steps: 1000           # Neural ODE: steps.
num_workers: 0
random_seed: 1
train_val_test_ratio: '6:2:2'
train_identity: False
